AppService.create(:id => 1, :name => "ByteBasic", :limit => 1)
AppService.create(:id => 2, :name => "ByteDeluxe", :limit => 10)
AppService.create(:id => 3, :name => "BytePremium", :limit => 0)
AppService.create(:id => 4, :name => "basic", :limit => 1)
AppService.create(:id => 5, :name => "deluxe", :limit => 10)
AppService.create(:id => 6, :name => "premium", :limit => 0)
AppService.create(:id => 7, :name => "ByteBeta")
AppService.create(:id => 8, :name => "hbhr")
AppService.create(:id => 9, :name => "BIGPKG")
AppService.create(:id => 10, :name => "byte")
