Category.create(:id => 43, :name => "Individual Combos", :location_id => 19)
Category.create(:id => 44, :name => "CHICKEN STRIPS", :location_id => 19)
Category.create(:id => 45, :name => "BONELESS & CLASSIC WINGS", :location_id => 19)
Category.create(:id => 46, :name => "SIDES", :location_id => 19)
Category.create(:id => 47, :name => "MONDAY COUPON", :location_id => 19)
Category.create(:id => 81, :name => "Combo Meals", :location_id => 46)
Category.create(:id => 82, :name => "Tender Family Meal", :location_id => 46)
Category.create(:id => 83, :name => "Chicken/Fish/Hot Wing Family  ", :location_id => 46)
Category.create(:id => 84, :name => "Fish Family Meals", :location_id => 46)
Category.create(:id => 85, :name => "Side Orders Regular Size", :location_id => 46)
Category.create(:id => 86, :name => "Appetizers", :location_id => 44, :category_points => 5)
Category.create(:id => 87, :name => "Salads", :location_id => 44, :category_points => 5)
Category.create(:id => 88, :name => "Burgers & Sandwiches", :location_id => 44, :category_points => 10)
Category.create(:id => 89, :name => "Plates", :location_id => 44, :category_points => 15)
Category.create(:id => 90, :name => "Desserts", :location_id => 44, :category_points => 5)
Category.create(:id => 91, :name => "Chef's Specials", :location_id => 44, :category_points => 10)
Category.create(:id => 92, :name => "Side Orders Family Size", :location_id => 46)
Category.create(:id => 93, :name => "Sauces and seasoning", :location_id => 46)
Category.create(:id => 94, :name => "Drinks", :location_id => 46)
Category.create(:id => 95, :name => "Large Drinks (32 oz.)", :location_id => 46)
Category.create(:id => 96, :name => "Jumbo Drinks (64 oz)", :location_id => 46)
Category.create(:id => 97, :name => "Dinner Meals", :location_id => 46)
Category.create(:id => 98, :name => "Gizzards & LIvers", :location_id => 46)
Category.create(:id => 99, :name => "Tenders", :location_id => 46)
Category.create(:id => 100, :name => "Fish", :location_id => 46)
Category.create(:id => 101, :name => "Hot Wings", :location_id => 46)
Category.create(:id => 102, :name => "Chicken With Biscuits", :location_id => 46)
Category.create(:id => 103, :name => "Catering", :location_id => 46)
Category.create(:id => 105, :name => "Bulk Catering Hot Wings", :location_id => 46)
Category.create(:id => 106, :name => "Bulk Catering Livers", :location_id => 46)
Category.create(:id => 107, :name => "Bulk Catering Gizzards", :location_id => 46)
Category.create(:id => 108, :name => " Catering Sides", :location_id => 46)
Category.create(:id => 109, :name => "COMBO SPECIAL", :location_id => 46)
Category.create(:id => 110, :name => "FUNDRAISER TIME", :location_id => 46)
Category.create(:id => 112, :name => "CHURCH ON THE ROCK SPECIAL", :location_id => 19)
Category.create(:id => 130, :name => "Combo Meals ", :location_id => 60, :category_points => 2)
Category.create(:id => 131, :name => "Dinners", :location_id => 60, :category_points => 2)
Category.create(:id => 132, :name => "Family Meals", :location_id => 60, :category_points => 2)
Category.create(:id => 133, :name => "Tenders", :location_id => 60, :category_points => 2)
Category.create(:id => 134, :name => "Bone Chicken", :location_id => 60, :category_points => 2)
Category.create(:id => 135, :name => "Livers/Gizzards", :location_id => 60, :category_points => 2)
Category.create(:id => 136, :name => "Fish", :location_id => 60, :category_points => 2)
Category.create(:id => 137, :name => "Hotwings", :location_id => 60, :category_points => 2)
Category.create(:id => 138, :name => "Side Orders", :location_id => 60, :category_points => 2)
Category.create(:id => 166, :name => "Breakfast Specials", :location_id => 84, :category_points => 10)
Category.create(:id => 167, :name => "OMELETS ", :location_id => 84)
Category.create(:id => 168, :name => "Breakfast Items", :location_id => 84)
Category.create(:id => 169, :name => "BREAKFAST SIDE ORDERS", :location_id => 84)
Category.create(:id => 170, :name => "DRINKS", :location_id => 84)
Category.create(:id => 171, :name => "LUNCH SPECIALS-MON-SUN", :location_id => 84)
Category.create(:id => 172, :name => "LUNCH MENU", :location_id => 84)
Category.create(:id => 173, :name => "LUNCH SIDES AND KIDS MEAL", :location_id => 84)
Category.create(:id => 174, :name => "Dinner Menu-Thur-Sun.", :location_id => 84)
Category.create(:id => 175, :name => "Dinner Hours Thur-Sun.", :location_id => 84)
Category.create(:id => 176, :name => "DINNER MENU & HOURS", :location_id => 84)
Category.create(:id => 177, :name => "APPETIZERS ", :location_id => 84)
Category.create(:id => 178, :name => "HAMBURGER & MORE", :location_id => 84)
Category.create(:id => 180, :name => "SALADS", :location_id => 84)
Category.create(:id => 181, :name => "Dinner Plates", :location_id => 84)
Category.create(:id => 182, :name => "DINNER SIDE ITEMS", :location_id => 84)
Category.create(:id => 183, :name => "Dessert", :location_id => 84)
Category.create(:id => 190, :name => "ALL DRINKS", :location_id => 46)
Category.create(:id => 192, :name => "BBQ Sandwiches", :location_id => 98)
Category.create(:id => 193, :name => "BBQ Meat Plates", :location_id => 98)
Category.create(:id => 194, :name => "Potatoes & Stuff", :location_id => 98)
Category.create(:id => 195, :name => "Big Jake's Sides", :location_id => 98)
Category.create(:id => 196, :name => "Kid's Stuff", :location_id => 98)
Category.create(:id => 197, :name => "Meat by the Pound", :location_id => 98)
Category.create(:id => 198, :name => "Meat Choices", :location_id => 98)
Category.create(:id => 199, :name => "Fried Pie Shop", :location_id => 98)
Category.create(:id => 200, :name => "Drinks", :location_id => 98)
Category.create(:id => 201, :name => "Catering", :location_id => 98)
Category.create(:id => 202, :name => "Combo Meals", :location_id => 100)
Category.create(:id => 203, :name => "Family Tenders-Chicken-Fish", :location_id => 100, :category_points => 0)
Category.create(:id => 204, :name => "Dinners", :location_id => 100)
Category.create(:id => 205, :name => "Sides--Regular & Family", :location_id => 100, :category_points => 0)
Category.create(:id => 206, :name => "Drinks", :location_id => 100, :category_points => 0)
Category.create(:id => 207, :name => "Kid's Meals", :location_id => 100, :category_points => 0)
Category.create(:id => 208, :name => "Coupons", :location_id => 100, :category_points => 0)
Category.create(:id => 209, :name => "Special Deals", :location_id => 100, :category_points => 0)
Category.create(:id => 210, :name => "Chicken with Biscuits", :location_id => 100, :category_points => 0)
Category.create(:id => 211, :name => "Hot Wings", :location_id => 100, :category_points => 0)
Category.create(:id => 212, :name => "Fish", :location_id => 100, :category_points => 0)
Category.create(:id => 213, :name => "Liver & Gizzards", :location_id => 100, :category_points => 0)
Category.create(:id => 214, :name => "name", :location_id => 0, :category_points => 0)
Category.create(:id => 216, :name => "Tenders Pieces", :location_id => 100, :category_points => 0)
Category.create(:id => 217, :name => "Sauces", :location_id => 100, :category_points => 0)
Category.create(:id => 218, :name => "Appetizers", :location_id => 134, :category_points => 10)
Category.create(:id => 219, :name => "Appetizers", :location_id => 106)
Category.create(:id => 220, :name => "Entrees", :location_id => 106)
Category.create(:id => 221, :name => "Desserts", :location_id => 106)
Category.create(:id => 222, :name => "Appetizer", :location_id => 107)
Category.create(:id => 223, :name => "Entree", :location_id => 107)
Category.create(:id => 224, :name => "Naan", :location_id => 107)
Category.create(:id => 225, :name => "Dessert", :location_id => 107)
Category.create(:id => 226, :name => "Starters", :location_id => 112)
Category.create(:id => 228, :name => "Starters", :location_id => 113)
Category.create(:id => 229, :name => "Entree", :location_id => 113)
Category.create(:id => 230, :name => "Starters", :location_id => 114)
Category.create(:id => 231, :name => "Entree", :location_id => 114)
Category.create(:id => 232, :name => "Starters", :location_id => 115)
Category.create(:id => 233, :name => "Entree", :location_id => 115)
Category.create(:id => 234, :name => "Appetizers", :location_id => 116)
Category.create(:id => 235, :name => "Entrees", :location_id => 116)
Category.create(:id => 236, :name => "Desserts", :location_id => 116)
Category.create(:id => 237, :name => "Entree", :location_id => 117)
Category.create(:id => 238, :name => "Amuse Bouche", :location_id => 127)
Category.create(:id => 239, :name => "First Course", :location_id => 127)
Category.create(:id => 240, :name => "Second Course", :location_id => 127)
Category.create(:id => 241, :name => "Third Course", :location_id => 127)
Category.create(:id => 242, :name => "Appetizers", :location_id => 119)
Category.create(:id => 243, :name => "Entree", :location_id => 119)
Category.create(:id => 244, :name => "Dessert", :location_id => 119)
Category.create(:id => 245, :name => "Gizzards-Livers-Hot Wings", :location_id => 100)
Category.create(:id => 246, :name => "Chicken with Biscuit", :location_id => 100)
Category.create(:id => 247, :name => "Salads", :location_id => 134, :category_points => 20)
Category.create(:id => 252, :name => "Appetizers", :location_id => 133)
Category.create(:id => 253, :name => "Entrees", :location_id => 133)
Category.create(:id => 254, :name => "Desserts", :location_id => 133)
Category.create(:id => 255, :name => "Cocktails", :location_id => 103)
Category.create(:id => 256, :name => "Entrees", :location_id => 103)
Category.create(:id => 257, :name => "Amuse Bouche", :location_id => 141)
Category.create(:id => 258, :name => "First Course", :location_id => 141)
Category.create(:id => 259, :name => "Second Course", :location_id => 141)
Category.create(:id => 260, :name => "Third Course", :location_id => 141)
Category.create(:id => 261, :name => "Starter", :location_id => 122)
Category.create(:id => 262, :name => "Entree", :location_id => 122)
Category.create(:id => 263, :name => "Dessert", :location_id => 122)
Category.create(:id => 264, :name => "Catering", :location_id => 100)
Category.create(:id => 265, :name => "Seasonings and Sauces", :location_id => 100)
Category.create(:id => 266, :name => "What About Dessert?????", :location_id => 100)
Category.create(:id => 267, :name => "College Student Coupon", :location_id => 100)
Category.create(:id => 268, :name => "Lunch Specials", :location_id => 100)
Category.create(:id => 269, :name => "Entree", :location_id => 144)
Category.create(:id => 270, :name => "Breakfast & Brunch", :location_id => 126)
Category.create(:id => 271, :name => "Lunch", :location_id => 126)
Category.create(:id => 272, :name => "Dinner", :location_id => 126)
Category.create(:id => 273, :name => "Desserts", :location_id => 126)
Category.create(:id => 274, :name => "Cocktails", :location_id => 143)
Category.create(:id => 275, :name => "Entrees", :location_id => 143)
Category.create(:id => 276, :name => "Frank Picks", :location_id => 142)
Category.create(:id => 277, :name => "Breakfast Tacos", :location_id => 142)
Category.create(:id => 278, :name => "Biscuits", :location_id => 142)
Category.create(:id => 279, :name => "Appetizers", :location_id => 140)
Category.create(:id => 280, :name => "Entrees", :location_id => 140)
Category.create(:id => 281, :name => "Dessert", :location_id => 140)
Category.create(:id => 282, :name => "Appetizer", :location_id => 132)
Category.create(:id => 283, :name => "Entree", :location_id => 132)
Category.create(:id => 284, :name => "Dessert", :location_id => 132)
Category.create(:id => 285, :name => "Sushi Rolls / Sashimi", :location_id => 131)
Category.create(:id => 286, :name => "Dessert", :location_id => 130)
Category.create(:id => 287, :name => "Appetizers", :location_id => 130)
Category.create(:id => 288, :name => "Entrees", :location_id => 130)
Category.create(:id => 289, :name => "Appetizers", :location_id => 131)
Category.create(:id => 290, :name => "Salads", :location_id => 125)
Category.create(:id => 291, :name => "Dessert", :location_id => 125)
Category.create(:id => 292, :name => "Cocktail", :location_id => 122)
Category.create(:id => 293, :name => "Appetizers", :location_id => 121)
Category.create(:id => 294, :name => "Cocktails", :location_id => 121)
Category.create(:id => 295, :name => "Dessert", :location_id => 121)
Category.create(:id => 296, :name => "Crispy Fried Chicken", :location_id => 118)
Category.create(:id => 297, :name => "Side Orders", :location_id => 118)
Category.create(:id => 298, :name => "Fried Chicken", :location_id => 145)
Category.create(:id => 299, :name => "Sides", :location_id => 145)
Category.create(:id => 300, :name => "Appetizer", :location_id => 111)
Category.create(:id => 301, :name => "Main", :location_id => 111)
Category.create(:id => 302, :name => "Dessert", :location_id => 111)
Category.create(:id => 303, :name => "Three Course Prefix", :location_id => 104)
Category.create(:id => 304, :name => "Eat Out for Good", :location_id => 129)
Category.create(:id => 305, :name => "Combos", :location_id => 153)
Category.create(:id => 306, :name => "Dinners", :location_id => 153)
Category.create(:id => 307, :name => "Kids Meals", :location_id => 153)
Category.create(:id => 308, :name => "Salad", :location_id => 120)
Category.create(:id => 309, :name => "Entree", :location_id => 120)
Category.create(:id => 310, :name => "Dessert", :location_id => 120)
Category.create(:id => 311, :name => "Cocktail", :location_id => 120)
Category.create(:id => 312, :name => "Lunch Special ", :location_id => 154)
Category.create(:id => 313, :name => "College Student Coupon", :location_id => 154)
Category.create(:id => 314, :name => "Combo Meals", :location_id => 154)
Category.create(:id => 315, :name => "Regular Side Items", :location_id => 153)
Category.create(:id => 316, :name => "Dinners", :location_id => 154)
Category.create(:id => 317, :name => "Sides--Regular and Family", :location_id => 154)
Category.create(:id => 318, :name => "Family Size Side Orders", :location_id => 153)
Category.create(:id => 319, :name => "Tenders", :location_id => 153)
Category.create(:id => 320, :name => "Fish", :location_id => 153)
Category.create(:id => 321, :name => "Gizzards & Livers", :location_id => 153)
Category.create(:id => 322, :name => "Family Chicken/Fish/Hot wings", :location_id => 153)
Category.create(:id => 323, :name => "Tenders ", :location_id => 153)
Category.create(:id => 324, :name => "Sauces and Seasonings", :location_id => 153)
Category.create(:id => 325, :name => "Drinks", :location_id => 153)
Category.create(:id => 326, :name => "Catering", :location_id => 153)
Category.create(:id => 327, :name => "Livers and Gizzards", :location_id => 154)
Category.create(:id => 331, :name => "Family Tenders-Chicken-Fish", :location_id => 154)
Category.create(:id => 332, :name => "Tenders Pieces", :location_id => 154)
Category.create(:id => 333, :name => "Fish", :location_id => 154)
Category.create(:id => 334, :name => "Drinks", :location_id => 154)
Category.create(:id => 335, :name => "Gizzards-Livers-Hot Wings", :location_id => 154)
Category.create(:id => 336, :name => "Chicken with Biscuit", :location_id => 154)
Category.create(:id => 337, :name => "Catering", :location_id => 154)
Category.create(:id => 338, :name => "SNACK PAC & KIDS MEAL", :location_id => 100)
Category.create(:id => 339, :name => "New Side- Mac n Cheese", :location_id => 100)
Category.create(:id => 340, :name => "Snack Pack/Kids' Meals", :location_id => 154)
Category.create(:id => 341, :name => "Snack Packs", :location_id => 154)
Category.create(:id => 342, :name => "DRINKS", :location_id => 154)
Category.create(:id => 343, :name => "Whats for Dessert????? ", :location_id => 154)
Category.create(:id => 346, :name => "Cow Tipping Famous Creamery.", :location_id => 161)
Category.create(:id => 347, :name => "Cow  Tipping Drinks", :location_id => 161)
Category.create(:id => 348, :name => "THANK YOU SO MUCH", :location_id => 161)
Category.create(:id => 349, :name => "Evil Wiener Famous Dishes", :location_id => 162)
Category.create(:id => 350, :name => "Evil Weiner Sides", :location_id => 162)
Category.create(:id => 351, :name => "Special of the Week", :location_id => 162)
Category.create(:id => 352, :name => "Drinks", :location_id => 162)
Category.create(:id => 353, :name => "Kabobl Tasty Meals", :location_id => 163)
Category.create(:id => 354, :name => "Salads", :location_id => 163)
Category.create(:id => 355, :name => "Drinks", :location_id => 163)
Category.create(:id => 356, :name => "INVITATION FOR YOU", :location_id => 163)
Category.create(:id => 357, :name => "PIZZA", :location_id => 164)
Category.create(:id => 358, :name => "Drinks", :location_id => 164)
Category.create(:id => 359, :name => "Thank you so much", :location_id => 164)
Category.create(:id => 360, :name => "Little Lucy's Mini Doughnuts", :location_id => 165)
Category.create(:id => 361, :name => "Drinks", :location_id => 165)
Category.create(:id => 362, :name => "We Appreciate You", :location_id => 165)
Category.create(:id => 363, :name => "Best Savente's Burgers", :location_id => 166)
Category.create(:id => 364, :name => "Spicy French Fries", :location_id => 166)
Category.create(:id => 365, :name => "Sides", :location_id => 166)
Category.create(:id => 366, :name => "Breakfast Burgers", :location_id => 166)
Category.create(:id => 367, :name => "FAMOUS TACOS", :location_id => 176)
Category.create(:id => 368, :name => "Breakfast taco", :location_id => 176)
Category.create(:id => 369, :name => "Drinks", :location_id => 176)
Category.create(:id => 371, :name => "Mini cheese cakes", :location_id => 177)
Category.create(:id => 372, :name => "Drinks", :location_id => 177)
Category.create(:id => 373, :name => "Italian Ices", :location_id => 179)
Category.create(:id => 374, :name => "Homemade Ice Cream", :location_id => 179)
Category.create(:id => 375, :name => "Cold Pressed Juice", :location_id => 180)
Category.create(:id => 376, :name => "FRESH JUICES", :location_id => 180)
Category.create(:id => 377, :name => "STANDARD JUICES", :location_id => 180)
Category.create(:id => 378, :name => "COME BY THE FOOD TRUCK", :location_id => 180)
Category.create(:id => 379, :name => "COME ON BY!!!!!!", :location_id => 181)
Category.create(:id => 380, :name => "SANDWICHES", :location_id => 181)
Category.create(:id => 381, :name => "FISH PLATES", :location_id => 181)
Category.create(:id => 382, :name => "Po Boys Delight", :location_id => 181)
Category.create(:id => 389, :name => "Specialty Doughnuts", :location_id => 185)
Category.create(:id => 390, :name => "Breakfast ", :location_id => 185)
Category.create(:id => 391, :name => "Lunch Menu", :location_id => 185)
Category.create(:id => 394, :name => "Special", :location_id => 186)
Category.create(:id => 395, :name => "The Plates", :location_id => 187)
Category.create(:id => 396, :name => "Catering", :location_id => 187)
Category.create(:id => 401, :name => "Catering", :location_id => 154)
Category.create(:id => 402, :name => "Samples", :location_id => 182)
Category.create(:id => 403, :name => "TXTW", :location_id => 190)
Category.create(:id => 404, :name => "Italian Ices", :location_id => 179)
Category.create(:id => 405, :name => "Ice Cream", :location_id => 179)
Category.create(:id => 406, :name => "Shakes", :location_id => 179)
Category.create(:id => 407, :name => "Shakes", :location_id => 179)
Category.create(:id => 408, :name => "Slushes & Shakes", :location_id => 179)
Category.create(:id => 409, :name => "The Beef Cake Food Truck menu", :location_id => 174)
Category.create(:id => 410, :name => "Hamburgers", :location_id => 174)
Category.create(:id => 411, :name => "Sandwiches", :location_id => 174)
Category.create(:id => 412, :name => "TXTW", :location_id => 191)
Category.create(:id => 413, :name => "TXTW", :location_id => 175)
Category.create(:id => 414, :name => "TXTW", :location_id => 174)
Category.create(:id => 415, :name => "TXTW", :location_id => 173)
Category.create(:id => 416, :name => "TXTW", :location_id => 172)
Category.create(:id => 417, :name => "TXTW", :location_id => 171)
Category.create(:id => 419, :name => "TXTW", :location_id => 168)
Category.create(:id => 420, :name => "TXTW", :location_id => 167)
Category.create(:id => 421, :name => "Wraps", :location_id => 192)
Category.create(:id => 422, :name => "Sides", :location_id => 192)
Category.create(:id => 423, :name => "Bocadillos", :location_id => 171)
Category.create(:id => 424, :name => "Bocadillos", :location_id => 171)
Category.create(:id => 425, :name => "Tacos", :location_id => 193)
Category.create(:id => 426, :name => "Specialties", :location_id => 193)
Category.create(:id => 427, :name => "Specialties", :location_id => 193)
Category.create(:id => 428, :name => "Machaca Beef", :location_id => 193)
Category.create(:id => 429, :name => "Main Selections", :location_id => 194)
Category.create(:id => 430, :name => "Main Dishes", :location_id => 194)
Category.create(:id => 431, :name => "Main Dishes", :location_id => 194)
Category.create(:id => 432, :name => "Catering", :location_id => 199)
Category.create(:id => 433, :name => "Main dishes", :location_id => 199)
Category.create(:id => 434, :name => "Main Dishes", :location_id => 200)
Category.create(:id => 435, :name => "TXTW", :location_id => 198)
Category.create(:id => 466, :name => "Tenders", :location_id => 205)
Category.create(:id => 467, :name => "Chicken", :location_id => 205)
Category.create(:id => 468, :name => "Fish", :location_id => 205)
Category.create(:id => 469, :name => "Hotwings", :location_id => 205)
Category.create(:id => 470, :name => "Livers and Gizzards", :location_id => 205)
Category.create(:id => 471, :name => "Sides", :location_id => 205)
Category.create(:id => 472, :name => "Beverages", :location_id => 205)
Category.create(:id => 473, :name => "Extras", :location_id => 205)
Category.create(:id => 474, :name => "Tenders", :location_id => 210)
Category.create(:id => 475, :name => "Chicken", :location_id => 210)
Category.create(:id => 476, :name => "Fish", :location_id => 210)
Category.create(:id => 477, :name => "Hot Wings", :location_id => 210)
Category.create(:id => 478, :name => "Livers & Gizzards", :location_id => 210)
Category.create(:id => 479, :name => "Sides", :location_id => 210)
Category.create(:id => 480, :name => "Drinks", :location_id => 210)
Category.create(:id => 481, :name => "Smoothies", :location_id => 210)
Category.create(:id => 482, :name => "Extras", :location_id => 210)
Category.create(:id => 483, :name => "YES WE CATER", :location_id => 211)
Category.create(:id => 484, :name => "TENDERS", :location_id => 211)
Category.create(:id => 485, :name => "CHICKEN", :location_id => 211)
Category.create(:id => 486, :name => "FISH", :location_id => 211)
Category.create(:id => 487, :name => "HOT WINGS", :location_id => 211)
Category.create(:id => 488, :name => "LIVERS & GIZZARDS", :location_id => 211)
Category.create(:id => 489, :name => "REGULAR SIDES", :location_id => 211)
Category.create(:id => 490, :name => "FAMILY SIDES", :location_id => 211)
Category.create(:id => 491, :name => " Tenders", :location_id => 212)
Category.create(:id => 492, :name => "Chicken", :location_id => 212)
Category.create(:id => 493, :name => "Fish", :location_id => 212)
Category.create(:id => 494, :name => "Hot Wings", :location_id => 212)
Category.create(:id => 495, :name => "Livers & Gizzards", :location_id => 212)
Category.create(:id => 496, :name => "Sides", :location_id => 212)
Category.create(:id => 497, :name => "Drinks", :location_id => 212)
Category.create(:id => 498, :name => "Smoothies", :location_id => 212)
Category.create(:id => 499, :name => "Extras", :location_id => 212)
Category.create(:id => 501, :name => "Lobster Rolls", :location_id => 172)
Category.create(:id => 502, :name => "Non-Lobster Rolls", :location_id => 172)
Category.create(:id => 503, :name => "Platters & Salads", :location_id => 172)
Category.create(:id => 504, :name => "Accomplice", :location_id => 172)
Category.create(:id => 505, :name => "SMOOTHIES", :location_id => 211)
Category.create(:id => 506, :name => "DRINKS", :location_id => 211)
Category.create(:id => 507, :name => "TXTW", :location_id => 213)
Category.create(:id => 508, :name => "SHAVED ICE", :location_id => 168)
Category.create(:id => 509, :name => "FOod", :location_id => 226, :category_points => 12)
Category.create(:id => 510, :name => "YES WE CATER", :location_id => 226)
Category.create(:id => 511, :name => "TENDERS", :location_id => 226)
Category.create(:id => 512, :name => "TENDERS", :location_id => 226)
Category.create(:id => 513, :name => "TENDERS", :location_id => 226)
Category.create(:id => 514, :name => "TENDERS", :location_id => 226)
Category.create(:id => 515, :name => "TENDERS", :location_id => 226)
Category.create(:id => 516, :name => "TENDERS", :location_id => 226)
Category.create(:id => 517, :name => "TENDERS", :location_id => 226)
Category.create(:id => 518, :name => "TENDERS", :location_id => 226)
Category.create(:id => 519, :name => "TENDERS", :location_id => 226)
Category.create(:id => 520, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 521, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 522, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 523, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 524, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 525, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 526, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 527, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 528, :name => "CHICKEN", :location_id => 226)
Category.create(:id => 529, :name => "FISH", :location_id => 226)
Category.create(:id => 530, :name => "FISH", :location_id => 226)
Category.create(:id => 531, :name => "FISH", :location_id => 226)
Category.create(:id => 532, :name => "FISH", :location_id => 226)
Category.create(:id => 533, :name => "FISH", :location_id => 226)
Category.create(:id => 534, :name => "FISH", :location_id => 226)
Category.create(:id => 535, :name => "FISH", :location_id => 226)
Category.create(:id => 536, :name => "HOT WINGS", :location_id => 226)
Category.create(:id => 537, :name => "HOT WINGS", :location_id => 226)
Category.create(:id => 538, :name => "HOT WINGS", :location_id => 226)
Category.create(:id => 539, :name => "HOT WINGS", :location_id => 226)
Category.create(:id => 540, :name => "HOT WINGS", :location_id => 226)
Category.create(:id => 541, :name => "LIVERS & GIZZARDS", :location_id => 226)
Category.create(:id => 542, :name => "LIVERS & GIZZARDS", :location_id => 226)
Category.create(:id => 543, :name => "LIVERS & GIZZARDS", :location_id => 226)
Category.create(:id => 544, :name => "LIVERS & GIZZARDS", :location_id => 226)
Category.create(:id => 545, :name => "LIVERS & GIZZARDS", :location_id => 226)
Category.create(:id => 546, :name => "LIVERS & GIZZARDS", :location_id => 226)
Category.create(:id => 547, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 548, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 549, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 550, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 551, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 552, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 553, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 554, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 555, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 556, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 557, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 558, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 559, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 560, :name => "REGULAR SIDES", :location_id => 226)
Category.create(:id => 561, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 562, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 563, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 564, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 565, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 566, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 567, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 568, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 569, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 570, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 571, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 572, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 573, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 574, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 575, :name => "FAMILY SIDES", :location_id => 226)
Category.create(:id => 576, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 577, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 578, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 579, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 580, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 581, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 582, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 583, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 584, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 585, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 586, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 587, :name => "SMOOTHIES", :location_id => 226)
Category.create(:id => 588, :name => "DRINKS", :location_id => 226)
Category.create(:id => 589, :name => "DRINKS", :location_id => 226)
Category.create(:id => 590, :name => "DRINKS", :location_id => 226)
Category.create(:id => 591, :name => "Hi", :location_id => 105, :redemption_value => 123)
Category.create(:id => 592, :name => "Hi", :location_id => 152, :redemption_value => 12)
Category.create(:id => 600, :name => "Fraser", :location_id => 225, :redemption_value => 123)
Category.create(:id => 601, :name => "Fraser", :location_id => 225, :redemption_value => 123)
Category.create(:id => 602, :name => "Fraser", :location_id => 228, :redemption_value => 123)
Category.create(:id => 604, :name => "Fraser", :location_id => 223, :redemption_value => 123)
Category.create(:id => 605, :name => "Fraser", :location_id => 219, :redemption_value => 123)
Category.create(:id => 606, :name => "Fraser", :location_id => 218, :redemption_value => 123)
Category.create(:id => 608, :name => "HI", :location_id => 216, :redemption_value => 123)
Category.create(:id => 609, :name => "HI", :location_id => 215, :redemption_value => 123)
Category.create(:id => 610, :name => "HI", :location_id => 215, :redemption_value => 123)
Category.create(:id => 611, :name => "HI", :location_id => 214, :redemption_value => 12)
Category.create(:id => 612, :name => "HI", :location_id => 208, :redemption_value => 123)
Category.create(:id => 613, :name => "fras", :location_id => 206, :redemption_value => 12)
Category.create(:id => 614, :name => "Fraser", :location_id => 207, :redemption_value => 123)
Category.create(:id => 615, :name => "Fraser", :location_id => 204, :redemption_value => 123)
Category.create(:id => 616, :name => "Fraser", :location_id => 196, :redemption_value => 123)
Category.create(:id => 617, :name => "Fraser", :location_id => 197, :redemption_value => 123)
Category.create(:id => 619, :name => "Fraser", :location_id => 158, :redemption_value => 123)
Category.create(:id => 620, :name => "Hi", :location_id => 158, :redemption_value => 123)
Category.create(:id => 621, :name => "Fraser", :location_id => 152, :redemption_value => 123)
Category.create(:id => 622, :name => "Fraser", :location_id => 135, :redemption_value => 123)
Category.create(:id => 623, :name => "Fraser", :location_id => 217, :redemption_value => 123)
Category.create(:id => 626, :name => "Fraser", :location_id => 221, :redemption_value => 123)
