ContactGroup.create(:id => 1, :title => "Rate", :description => "Rate")
ContactGroup.create(:id => 2, :title => "Set Favorite", :description => "Set Favorite")
ContactGroup.create(:id => 3, :title => "Share Menu Items", :description => "Share Menu Items")
ContactGroup.create(:id => 4, :title => "Share Restaurant Points", :description => "Share Restaurant Points")
ContactGroup.create(:id => 5, :title => "Order", :description => "Order")
ContactGroup.create(:id => 6, :title => "Pay", :description => "Pay")
ContactGroup.create(:id => 7, :title => "Accept Points", :description => "Accept Points")
ContactGroup.create(:id => 8, :title => "Restaurant", :description => "Restaurant")
ContactGroup.create(:id => 9, :title => "Diner", :description => "Diner")
