Country.create(:id => 1, :country_code => "AD", :name => "Andorra")
Country.create(:id => 2, :country_code => "AE", :name => "United Arab Emirates")
Country.create(:id => 3, :country_code => "AF", :name => "Afghanistan")
Country.create(:id => 4, :country_code => "AG", :name => "Antigua and Barbuda")
Country.create(:id => 5, :country_code => "AI", :name => "Anguilla")
Country.create(:id => 6, :country_code => "AL", :name => "Albania")
Country.create(:id => 7, :country_code => "AM", :name => "Armenia")
Country.create(:id => 8, :country_code => "AN", :name => "Netherlands Antilles")
Country.create(:id => 9, :country_code => "AO", :name => "Angola")
Country.create(:id => 10, :country_code => "AQ", :name => "Antarctica")
Country.create(:id => 11, :country_code => "AR", :name => "Argentina")
Country.create(:id => 12, :country_code => "AS", :name => "American Samoa")
Country.create(:id => 13, :country_code => "AT", :name => "Austria")
Country.create(:id => 14, :country_code => "AU", :name => "Australia")
Country.create(:id => 15, :country_code => "AW", :name => "Aruba")
Country.create(:id => 16, :country_code => "AX", :name => "Åland Islands")
Country.create(:id => 17, :country_code => "AZ", :name => "Azerbaijan")
Country.create(:id => 18, :country_code => "BA", :name => "Bosnia and Herzegovina")
Country.create(:id => 19, :country_code => "BB", :name => "Barbados")
Country.create(:id => 20, :country_code => "BD", :name => "Bangladesh")
Country.create(:id => 21, :country_code => "BE", :name => "Belgium")
Country.create(:id => 22, :country_code => "BF", :name => "Burkina Faso")
Country.create(:id => 23, :country_code => "BG", :name => "Bulgaria")
Country.create(:id => 24, :country_code => "BH", :name => "Bahrain")
Country.create(:id => 25, :country_code => "BI", :name => "Burundi")
Country.create(:id => 26, :country_code => "BJ", :name => "Benin")
Country.create(:id => 27, :country_code => "BL", :name => "Saint Barthélemy")
Country.create(:id => 28, :country_code => "BM", :name => "Bermuda")
Country.create(:id => 29, :country_code => "BN", :name => "Brunei")
Country.create(:id => 30, :country_code => "BO", :name => "Bolivia")
Country.create(:id => 31, :country_code => "BQ", :name => "British Antarctic Territory")
Country.create(:id => 32, :country_code => "BR", :name => "Brazil")
Country.create(:id => 33, :country_code => "BS", :name => "Bahamas")
Country.create(:id => 34, :country_code => "BT", :name => "Bhutan")
Country.create(:id => 35, :country_code => "BV", :name => "Bouvet Island")
Country.create(:id => 36, :country_code => "BW", :name => "Botswana")
Country.create(:id => 37, :country_code => "BY", :name => "Belarus")
Country.create(:id => 38, :country_code => "BZ", :name => "Belize")
Country.create(:id => 39, :country_code => "CA", :name => "Canada")
Country.create(:id => 40, :country_code => "CC", :name => "Cocos [Keeling] Islands")
Country.create(:id => 41, :country_code => "CD", :name => "Congo - Kinshasa")
Country.create(:id => 42, :country_code => "CF", :name => "Central African Republic")
Country.create(:id => 43, :country_code => "CG", :name => "Congo - Brazzaville")
Country.create(:id => 44, :country_code => "CH", :name => "Switzerland")
Country.create(:id => 45, :country_code => "CI", :name => "Côte d’Ivoire")
Country.create(:id => 46, :country_code => "CK", :name => "Cook Islands")
Country.create(:id => 47, :country_code => "CL", :name => "Chile")
Country.create(:id => 48, :country_code => "CM", :name => "Cameroon")
Country.create(:id => 49, :country_code => "CN", :name => "China")
Country.create(:id => 50, :country_code => "CO", :name => "Colombia")
Country.create(:id => 51, :country_code => "CR", :name => "Costa Rica")
Country.create(:id => 52, :country_code => "CS", :name => "Serbia and Montenegro")
Country.create(:id => 53, :country_code => "CT", :name => "Canton and Enderbury Islands")
Country.create(:id => 54, :country_code => "CU", :name => "Cuba")
Country.create(:id => 55, :country_code => "CV", :name => "Cape Verde")
Country.create(:id => 56, :country_code => "CX", :name => "Christmas Island")
Country.create(:id => 57, :country_code => "CY", :name => "Cyprus")
Country.create(:id => 58, :country_code => "CZ", :name => "Czech Republic")
Country.create(:id => 59, :country_code => "DD", :name => "East Germany")
Country.create(:id => 60, :country_code => "DE", :name => "Germany")
Country.create(:id => 61, :country_code => "DJ", :name => "Djibouti")
Country.create(:id => 62, :country_code => "DK", :name => "Denmark")
Country.create(:id => 63, :country_code => "DM", :name => "Dominica")
Country.create(:id => 64, :country_code => "DO", :name => "Dominican Republic")
Country.create(:id => 65, :country_code => "DZ", :name => "Algeria")
Country.create(:id => 66, :country_code => "EC", :name => "Ecuador")
Country.create(:id => 67, :country_code => "EE", :name => "Estonia")
Country.create(:id => 68, :country_code => "EG", :name => "Egypt")
Country.create(:id => 69, :country_code => "EH", :name => "Western Sahara")
Country.create(:id => 70, :country_code => "ER", :name => "Eritrea")
Country.create(:id => 71, :country_code => "ES", :name => "Spain")
Country.create(:id => 72, :country_code => "ET", :name => "Ethiopia")
Country.create(:id => 73, :country_code => "FI", :name => "Finland")
Country.create(:id => 74, :country_code => "FJ", :name => "Fiji")
Country.create(:id => 75, :country_code => "FK", :name => "Falkland Islands")
Country.create(:id => 76, :country_code => "FM", :name => "Micronesia")
Country.create(:id => 77, :country_code => "FO", :name => "Faroe Islands")
Country.create(:id => 78, :country_code => "FQ", :name => "French Southern and Antarctic Territories")
Country.create(:id => 79, :country_code => "FR", :name => "France")
Country.create(:id => 80, :country_code => "FX", :name => "Metropolitan France")
Country.create(:id => 81, :country_code => "GA", :name => "Gabon")
Country.create(:id => 82, :country_code => "GB", :name => "United Kingdom")
Country.create(:id => 83, :country_code => "GD", :name => "Grenada")
Country.create(:id => 84, :country_code => "GE", :name => "Georgia")
Country.create(:id => 85, :country_code => "GF", :name => "French Guiana")
Country.create(:id => 86, :country_code => "GG", :name => "Guernsey")
Country.create(:id => 87, :country_code => "GH", :name => "Ghana")
Country.create(:id => 88, :country_code => "GI", :name => "Gibraltar")
Country.create(:id => 89, :country_code => "GL", :name => "Greenland")
Country.create(:id => 90, :country_code => "GM", :name => "Gambia")
Country.create(:id => 91, :country_code => "GN", :name => "Guinea")
Country.create(:id => 92, :country_code => "GP", :name => "Guadeloupe")
Country.create(:id => 93, :country_code => "GQ", :name => "Equatorial Guinea")
Country.create(:id => 94, :country_code => "GR", :name => "Greece")
Country.create(:id => 95, :country_code => "GS", :name => "South Georgia and the South Sandwich Islands")
Country.create(:id => 96, :country_code => "GT", :name => "Guatemala")
Country.create(:id => 97, :country_code => "GU", :name => "Guam")
Country.create(:id => 98, :country_code => "GW", :name => "Guinea-Bissau")
Country.create(:id => 99, :country_code => "GY", :name => "Guyana")
Country.create(:id => 100, :country_code => "HK", :name => "Hong Kong SAR China")
Country.create(:id => 101, :country_code => "HM", :name => "Heard Island and McDonald Islands")
Country.create(:id => 102, :country_code => "HN", :name => "Honduras")
Country.create(:id => 103, :country_code => "HR", :name => "Croatia")
Country.create(:id => 104, :country_code => "HT", :name => "Haiti")
Country.create(:id => 105, :country_code => "HU", :name => "Hungary")
Country.create(:id => 106, :country_code => "ID", :name => "Indonesia")
Country.create(:id => 107, :country_code => "IE", :name => "Ireland")
Country.create(:id => 108, :country_code => "IL", :name => "Israel")
Country.create(:id => 109, :country_code => "IM", :name => "Isle of Man")
Country.create(:id => 110, :country_code => "IN", :name => "India")
Country.create(:id => 111, :country_code => "IO", :name => "British Indian Ocean Territory")
Country.create(:id => 112, :country_code => "IQ", :name => "Iraq")
Country.create(:id => 113, :country_code => "IR", :name => "Iran")
Country.create(:id => 114, :country_code => "IS", :name => "Iceland")
Country.create(:id => 115, :country_code => "IT", :name => "Italy")
Country.create(:id => 116, :country_code => "JE", :name => "Jersey")
Country.create(:id => 117, :country_code => "JM", :name => "Jamaica")
Country.create(:id => 118, :country_code => "JO", :name => "Jordan")
Country.create(:id => 119, :country_code => "JP", :name => "Japan")
Country.create(:id => 120, :country_code => "JT", :name => "Johnston Island")
Country.create(:id => 121, :country_code => "KE", :name => "Kenya")
Country.create(:id => 122, :country_code => "KG", :name => "Kyrgyzstan")
Country.create(:id => 123, :country_code => "KH", :name => "Cambodia")
Country.create(:id => 124, :country_code => "KI", :name => "Kiribati")
Country.create(:id => 125, :country_code => "KM", :name => "Comoros")
Country.create(:id => 126, :country_code => "KN", :name => "Saint Kitts and Nevis")
Country.create(:id => 127, :country_code => "KP", :name => "North Korea")
Country.create(:id => 128, :country_code => "KR", :name => "South Korea")
Country.create(:id => 129, :country_code => "KW", :name => "Kuwait")
Country.create(:id => 130, :country_code => "KY", :name => "Cayman Islands")
Country.create(:id => 131, :country_code => "KZ", :name => "Kazakhstan")
Country.create(:id => 132, :country_code => "LA", :name => "Laos")
Country.create(:id => 133, :country_code => "LB", :name => "Lebanon")
Country.create(:id => 134, :country_code => "LC", :name => "Saint Lucia")
Country.create(:id => 135, :country_code => "LI", :name => "Liechtenstein")
Country.create(:id => 136, :country_code => "LK", :name => "Sri Lanka")
Country.create(:id => 137, :country_code => "LR", :name => "Liberia")
Country.create(:id => 138, :country_code => "LS", :name => "Lesotho")
Country.create(:id => 139, :country_code => "LT", :name => "Lithuania")
Country.create(:id => 140, :country_code => "LU", :name => "Luxembourg")
Country.create(:id => 141, :country_code => "LV", :name => "Latvia")
Country.create(:id => 142, :country_code => "LY", :name => "Libya")
Country.create(:id => 143, :country_code => "MA", :name => "Morocco")
Country.create(:id => 144, :country_code => "MC", :name => "Monaco")
Country.create(:id => 145, :country_code => "MD", :name => "Moldova")
Country.create(:id => 146, :country_code => "ME", :name => "Montenegro")
Country.create(:id => 147, :country_code => "MF", :name => "Saint Martin")
Country.create(:id => 148, :country_code => "MG", :name => "Madagascar")
Country.create(:id => 149, :country_code => "MH", :name => "Marshall Islands")
Country.create(:id => 150, :country_code => "MI", :name => "Midway Islands")
Country.create(:id => 151, :country_code => "MK", :name => "Macedonia")
Country.create(:id => 152, :country_code => "ML", :name => "Mali")
Country.create(:id => 153, :country_code => "MM", :name => "Myanmar [Burma]")
Country.create(:id => 154, :country_code => "MN", :name => "Mongolia")
Country.create(:id => 155, :country_code => "MO", :name => "Macau SAR China")
Country.create(:id => 156, :country_code => "MP", :name => "Northern Mariana Islands")
Country.create(:id => 157, :country_code => "MQ", :name => "Martinique")
Country.create(:id => 158, :country_code => "MR", :name => "Mauritania")
Country.create(:id => 159, :country_code => "MS", :name => "Montserrat")
Country.create(:id => 160, :country_code => "MT", :name => "Malta")
Country.create(:id => 161, :country_code => "MU", :name => "Mauritius")
Country.create(:id => 162, :country_code => "MV", :name => "Maldives")
Country.create(:id => 163, :country_code => "MW", :name => "Malawi")
Country.create(:id => 164, :country_code => "MX", :name => "Mexico")
Country.create(:id => 165, :country_code => "MY", :name => "Malaysia")
Country.create(:id => 166, :country_code => "MZ", :name => "Mozambique")
Country.create(:id => 167, :country_code => "NA", :name => "Namibia")
Country.create(:id => 168, :country_code => "NC", :name => "New Caledonia")
Country.create(:id => 169, :country_code => "NE", :name => "Niger")
Country.create(:id => 170, :country_code => "NF", :name => "Norfolk Island")
Country.create(:id => 171, :country_code => "NG", :name => "Nigeria")
Country.create(:id => 172, :country_code => "NI", :name => "Nicaragua")
Country.create(:id => 173, :country_code => "NL", :name => "Netherlands")
Country.create(:id => 174, :country_code => "NO", :name => "Norway")
Country.create(:id => 175, :country_code => "NP", :name => "Nepal")
Country.create(:id => 176, :country_code => "NQ", :name => "Dronning Maud Land")
Country.create(:id => 177, :country_code => "NR", :name => "Nauru")
Country.create(:id => 178, :country_code => "NT", :name => "Neutral Zone")
Country.create(:id => 179, :country_code => "NU", :name => "Niue")
Country.create(:id => 180, :country_code => "NZ", :name => "New Zealand")
Country.create(:id => 181, :country_code => "OM", :name => "Oman")
Country.create(:id => 182, :country_code => "PA", :name => "Panama")
Country.create(:id => 183, :country_code => "PC", :name => "Pacific Islands Trust Territory")
Country.create(:id => 184, :country_code => "PE", :name => "Peru")
Country.create(:id => 185, :country_code => "PF", :name => "French Polynesia")
Country.create(:id => 186, :country_code => "PG", :name => "Papua New Guinea")
Country.create(:id => 187, :country_code => "PH", :name => "Philippines")
Country.create(:id => 188, :country_code => "PK", :name => "Pakistan")
Country.create(:id => 189, :country_code => "PL", :name => "Poland")
Country.create(:id => 190, :country_code => "PM", :name => "Saint Pierre and Miquelon")
Country.create(:id => 191, :country_code => "PN", :name => "Pitcairn Islands")
Country.create(:id => 192, :country_code => "PR", :name => "Puerto Rico")
Country.create(:id => 193, :country_code => "PS", :name => "Palestinian Territories")
Country.create(:id => 194, :country_code => "PT", :name => "Portugal")
Country.create(:id => 195, :country_code => "PU", :name => "U.S. Miscellaneous Pacific Islands")
Country.create(:id => 196, :country_code => "PW", :name => "Palau")
Country.create(:id => 197, :country_code => "PY", :name => "Paraguay")
Country.create(:id => 198, :country_code => "PZ", :name => "Panama Canal Zone")
Country.create(:id => 199, :country_code => "QA", :name => "Qatar")
Country.create(:id => 200, :country_code => "RE", :name => "Réunion")
Country.create(:id => 201, :country_code => "RO", :name => "Romania")
Country.create(:id => 202, :country_code => "RS", :name => "Serbia")
Country.create(:id => 203, :country_code => "RU", :name => "Russia")
Country.create(:id => 204, :country_code => "RW", :name => "Rwanda")
Country.create(:id => 205, :country_code => "SA", :name => "Saudi Arabia")
Country.create(:id => 206, :country_code => "SB", :name => "Solomon Islands")
Country.create(:id => 207, :country_code => "SC", :name => "Seychelles")
Country.create(:id => 208, :country_code => "SD", :name => "Sudan")
Country.create(:id => 209, :country_code => "SE", :name => "Sweden")
Country.create(:id => 210, :country_code => "SG", :name => "Singapore")
Country.create(:id => 211, :country_code => "SH", :name => "Saint Helena")
Country.create(:id => 212, :country_code => "SI", :name => "Slovenia")
Country.create(:id => 213, :country_code => "SJ", :name => "Svalbard and Jan Mayen")
Country.create(:id => 214, :country_code => "SK", :name => "Slovakia")
Country.create(:id => 215, :country_code => "SL", :name => "Sierra Leone")
Country.create(:id => 216, :country_code => "SM", :name => "San Marino")
Country.create(:id => 217, :country_code => "SN", :name => "Senegal")
Country.create(:id => 218, :country_code => "SO", :name => "Somalia")
Country.create(:id => 219, :country_code => "SR", :name => "Suriname")
Country.create(:id => 220, :country_code => "ST", :name => "São Tomé and Príncipe")
Country.create(:id => 221, :country_code => "SU", :name => "Union of Soviet Socialist Republics")
Country.create(:id => 222, :country_code => "SV", :name => "El Salvador")
Country.create(:id => 223, :country_code => "SY", :name => "Syria")
Country.create(:id => 224, :country_code => "SZ", :name => "Swaziland")
Country.create(:id => 225, :country_code => "TC", :name => "Turks and Caicos Islands")
Country.create(:id => 226, :country_code => "TD", :name => "Chad")
Country.create(:id => 227, :country_code => "TF", :name => "French Southern Territories")
Country.create(:id => 228, :country_code => "TG", :name => "Togo")
Country.create(:id => 229, :country_code => "TH", :name => "Thailand")
Country.create(:id => 230, :country_code => "TJ", :name => "Tajikistan")
Country.create(:id => 231, :country_code => "TK", :name => "Tokelau")
Country.create(:id => 232, :country_code => "TL", :name => "Timor-Leste")
Country.create(:id => 233, :country_code => "TM", :name => "Turkmenistan")
Country.create(:id => 234, :country_code => "TN", :name => "Tunisia")
Country.create(:id => 235, :country_code => "TO", :name => "Tonga")
Country.create(:id => 236, :country_code => "TR", :name => "Turkey")
Country.create(:id => 237, :country_code => "TT", :name => "Trinidad and Tobago")
Country.create(:id => 238, :country_code => "TV", :name => "Tuvalu")
Country.create(:id => 239, :country_code => "TW", :name => "Taiwan")
Country.create(:id => 240, :country_code => "TZ", :name => "Tanzania")
Country.create(:id => 241, :country_code => "UA", :name => "Ukraine")
Country.create(:id => 242, :country_code => "UG", :name => "Uganda")
Country.create(:id => 243, :country_code => "UM", :name => "U.S. Minor Outlying Islands")
Country.create(:id => 244, :country_code => "US", :name => "United States")
Country.create(:id => 245, :country_code => "UY", :name => "Uruguay")
Country.create(:id => 246, :country_code => "UZ", :name => "Uzbekistan")
Country.create(:id => 247, :country_code => "VA", :name => "Vatican City")
Country.create(:id => 248, :country_code => "VC", :name => "Saint Vincent and the Grenadines")
Country.create(:id => 249, :country_code => "VD", :name => "North Vietnam")
Country.create(:id => 250, :country_code => "VE", :name => "Venezuela")
Country.create(:id => 251, :country_code => "VG", :name => "British Virgin Islands")
Country.create(:id => 252, :country_code => "VI", :name => "U.S. Virgin Islands")
Country.create(:id => 253, :country_code => "VN", :name => "Vietnam")
Country.create(:id => 254, :country_code => "VU", :name => "Vanuatu")
Country.create(:id => 255, :country_code => "WF", :name => "Wallis and Futuna")
Country.create(:id => 256, :country_code => "WK", :name => "Wake Island")
Country.create(:id => 257, :country_code => "WS", :name => "Samoa")
Country.create(:id => 258, :country_code => "YD", :name => "Peoples Democratic Republic of Yemen")
Country.create(:id => 259, :country_code => "YE", :name => "Yemen")
Country.create(:id => 260, :country_code => "YT", :name => "Mayotte")
Country.create(:id => 261, :country_code => "ZA", :name => "South Africa")
Country.create(:id => 262, :country_code => "ZM", :name => "Zambia")
Country.create(:id => 263, :country_code => "ZW", :name => "Zimbabwe")
Country.create(:id => 264, :country_code => "ZZ", :name => "Unknown or Invalid Region")
