CuisineType.create(:id => 1, :name => "American")
CuisineType.create(:id => 2, :name => "Asian")
CuisineType.create(:id => 3, :name => "Bar Food")
CuisineType.create(:id => 4, :name => "BBQ")
CuisineType.create(:id => 5, :name => "Cajun & Creole")
CuisineType.create(:id => 6, :name => "Chinese Cuban")
CuisineType.create(:id => 7, :name => "English")
CuisineType.create(:id => 8, :name => "Ethiopian")
CuisineType.create(:id => 9, :name => "French")
CuisineType.create(:id => 10, :name => "Fusion")
CuisineType.create(:id => 11, :name => "German Greek")
CuisineType.create(:id => 12, :name => "Hawaiian")
CuisineType.create(:id => 13, :name => "Hungarian")
CuisineType.create(:id => 14, :name => "Indian")
CuisineType.create(:id => 15, :name => "Irish")
CuisineType.create(:id => 16, :name => "Italian")
CuisineType.create(:id => 17, :name => "Japanese")
CuisineType.create(:id => 18, :name => "Mediterranean")
CuisineType.create(:id => 19, :name => "Mexican Moroccan")
CuisineType.create(:id => 20, :name => "Portuguese")
CuisineType.create(:id => 21, :name => "Seafood Southern & Soul Food")
CuisineType.create(:id => 22, :name => "Southwestern")
CuisineType.create(:id => 23, :name => "Spanish Steakhouse")
CuisineType.create(:id => 24, :name => "Swedish Thai")
